basePath: /
host: localhost:8080
info:
  contact:
    email: majabojarska98@gmail.com
    name: Maja Bojarska
    url: https://github.com/majabojarska/fibo
  description: Fibonacci sequence REST API
  license:
    name: MIT License
    url: https://github.com/majabojarska/fibo?tab=MIT-1-ov-file#readme
  title: Fibo
  version: "1.0"
paths: {}
swagger: "2.0"
